version: '3.9'

services:
  backend:
    build: .
    container_name: seo-neuroai-backend
    ports:
      - '8000:8000'
    volumes:
      - .:/app

  frontend:
    image: node:20
    container_name: seo-neuroai-frontend
    working_dir: /frontend
    command: sh -c 'npm install && npm start'
    ports:
      - '19000:19000'
    volumes:
      - ./frontend:/frontend
