import type { AccountRule } from "./types";

export const accountRules: AccountRule[] = [
  {
    code: "11",
    name: "Caixa",
    keywords: ["caixa", "numerario", "numerário", "dinheiro", "fundo de caixa"],
    defaultType: "Débito",
    reason: "Movimento associado a caixa, numerário ou fundo de caixa.",
  },
  {
    code: "12",
    name: "Depósitos à ordem",
    keywords: ["transferencia", "transferência", "banco", "mb way", "terminal", "tpa", "deposito", "depósito"],
    defaultType: "Débito",
    reason: "Movimento associado a conta bancária ou meios de pagamento.",
  },
  {
    code: "21",
    name: "Clientes",
    keywords: ["cliente", "recebimento", "fatura cliente", "factura cliente", "recibo", "conta corrente cliente"],
    defaultType: "Débito",
    reason: "Movimento relacionado com valores a receber de clientes.",
  },
  {
    code: "22",
    name: "Fornecedores",
    keywords: ["fornecedor", "pagamento fornecedor", "fatura fornecedor", "factura fornecedor", "compra fornecedor"],
    defaultType: "Crédito",
    reason: "Movimento relacionado com valores a pagar a fornecedores.",
  },
  {
    code: "24",
    name: "Estado e outros entes públicos",
    keywords: ["iva", "seguranca social", "segurança social", "at", "financas", "finanças", "imposto", "retencao", "retenção", "irc"],
    defaultType: "Crédito",
    reason: "Movimento fiscal, contributivo ou relativo a entidades públicas.",
  },
  {
    code: "31",
    name: "Compras",
    keywords: ["compra", "mercadoria", "pecas", "peças", "stock", "inventario", "inventário", "sucata", "viatura para peças"],
    defaultType: "Débito",
    reason: "Aquisição de mercadorias ou peças destinadas a venda.",
  },
  {
    code: "32",
    name: "Mercadorias",
    keywords: ["mercadorias", "inventario final", "inventário final", "existencias", "existências", "armazem", "armazém"],
    defaultType: "Débito",
    reason: "Movimento associado a mercadorias e existências.",
  },
  {
    code: "61",
    name: "Custo das mercadorias vendidas e das matérias consumidas",
    keywords: ["cmv", "cmvmc", "custo mercadoria", "custo das vendas", "custo produto", "custo peca", "custo peça"],
    defaultType: "Débito",
    reason: "Custo associado às mercadorias vendidas ou consumidas.",
  },
  {
    code: "62",
    name: "Fornecimentos e serviços externos",
    keywords: ["renda", "energia", "eletricidade", "electricidade", "agua", "água", "internet", "telefone", "seguro", "transporte", "combustivel", "combustível", "software", "comissao", "comissão", "ovoko", "recambio", "shopify", "woocommerce"],
    defaultType: "Débito",
    reason: "Gasto operacional externo associado à atividade.",
  },
  {
    code: "63",
    name: "Gastos com o pessoal",
    keywords: ["salario", "salário", "ordenado", "vencimento", "subsidio", "subsídio", "colaborador", "funcionario", "funcionário"],
    defaultType: "Débito",
    reason: "Gasto com trabalhadores ou remunerações.",
  },
  {
    code: "68",
    name: "Outros gastos e perdas",
    keywords: ["multa", "coima", "juros", "perda", "regularizacao", "regularização", "imparidade"],
    defaultType: "Débito",
    reason: "Gasto não enquadrado nas categorias operacionais principais.",
  },
  {
    code: "71",
    name: "Vendas",
    keywords: ["venda", "loja online", "loja fisica", "loja física", "marketplace", "produto vendido", "ovoko venda", "recambio venda"],
    defaultType: "Crédito",
    reason: "Rendimento proveniente da venda de mercadorias.",
  },
  {
    code: "72",
    name: "Prestações de serviços",
    keywords: ["servico", "serviço", "mao de obra", "mão de obra", "reparacao", "reparação", "diagnostico", "diagnóstico"],
    defaultType: "Crédito",
    reason: "Rendimento associado a prestação de serviços.",
  },
  {
    code: "78",
    name: "Outros rendimentos e ganhos",
    keywords: ["ganho", "indemnizacao", "indemnização", "regularizacao positiva", "regularização positiva"],
    defaultType: "Crédito",
    reason: "Rendimento não enquadrado nas categorias comerciais principais.",
  },
];
