from dataclasses import dataclass
from typing import Dict, List


@dataclass
class NeuroSignal:
    attention_score: float
    anomaly_score: float
    confidence_score: float
    recommended_action: str


class NeuroAIEngine:
    """
    NeuroAI Engine

    This module is inspired by cognitive principles used in neurotechnology:
    attention, memory, pattern recognition, adaptive learning and anomaly detection.

    It does not process medical neural data. It applies neuro-inspired reasoning
    to financial and operational business data.
    """

    def classify_document(self, description: str, amount: float) -> Dict:
        text = description.lower()

        if any(word in text for word in ['consultoria', 'software', 'serviço', 'servicos', 'serviços']):
            category = 'Serviços Externos'
        elif any(word in text for word in ['renda', 'aluguer', 'escritório', 'escritorio']):
            category = 'Instalações e Rendas'
        elif any(word in text for word in ['combustível', 'combustivel', 'transporte', 'uber', 'bolt']):
            category = 'Transportes e Deslocações'
        elif any(word in text for word in ['material', 'equipamento', 'computador']):
            category = 'Materiais e Equipamentos'
        else:
            category = 'Despesa Operacional Geral'

        confidence = 0.72
        if category != 'Despesa Operacional Geral':
            confidence = 0.91
        if amount > 1000:
            confidence = min(confidence + 0.03, 0.97)

        return {
            'category': category,
            'confidence_score': confidence,
            'reasoning': 'Classification generated by neuro-inspired pattern recognition.'
        }

    def analyze_financial_state(self, documents: List[Dict]) -> Dict:
        total = sum(doc.get('amount', 0) for doc in documents)
        average = total / len(documents) if documents else 0
        high_value_docs = [doc for doc in documents if doc.get('amount', 0) > average * 1.8] if average else []

        attention_score = min(len(high_value_docs) * 0.25 + 0.35, 0.99)
        anomaly_score = min(len(high_value_docs) * 0.30, 0.99)

        if anomaly_score > 0.7:
            action = 'Review high-value expenses and request human validation.'
        elif attention_score > 0.5:
            action = 'Monitor expense concentration and supplier patterns.'
        else:
            action = 'Financial pattern appears stable.'

        return {
            'total_expenses': total,
            'average_expense': average,
            'attention_score': round(attention_score, 2),
            'anomaly_score': round(anomaly_score, 2),
            'high_value_documents': len(high_value_docs),
            'recommended_action': action
        }

    def generate_executive_insight(self, company_id: int, documents: List[Dict]) -> Dict:
        state = self.analyze_financial_state(documents)

        if state['anomaly_score'] > 0.7:
            insight = 'The company shows relevant expense anomalies that require managerial review.'
        elif state['attention_score'] > 0.5:
            insight = 'The company has expense patterns that deserve attention, especially recurring or high-value costs.'
        else:
            insight = 'The company financial operations appear stable based on current documents.'

        return {
            'company_id': company_id,
            'neuro_ai_summary': insight,
            'cognitive_layer': {
                'attention': state['attention_score'],
                'anomaly': state['anomaly_score'],
                'memory_pattern': 'expense_history',
                'adaptive_learning': 'enabled_for_future_feedback'
            },
            'recommended_action': state['recommended_action']
        }


neuro_ai_engine = NeuroAIEngine()
